AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Layout/LineLength:
  Max: 260